[tool.black]
line-length = 100
extend-ignore = "E203"
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
include_trailing_comma = true

[tool.pylint.messages_control]
disable="""
R,C,W,E
"""
enable = """
import-error,unused-import
"""

[tool.bandit]
skips = ["B101"]