channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.9.15
  - pip==22.3.1
  - pytorch==2.1.0
  - pip:
    - absl-py==1.4.0
    - click==8.1.7
    - jax==0.4.17
    - jaxlib==0.4.17
    - ml-collections==0.1.1
    - optax==0.1.7
    - ott-jax==0.4.4
    - pandas==2.1.3
    - sbi==0.21.0
    - sbibm==1.1.0
    - future==1.0.0
    - git+https://github.com/dirmeier/sbijax.git@v0.1.3


