channels:
  - conda-forge
dependencies:
  - python==3.9.15
  - pip==22.3.1
  - pip:
    - absl-py==1.4.0
    - chex==0.1.83
    - distrax==0.1.4
    - dm-haiku==0.0.10
    - dm-tree==0.1.8
    - jax==0.4.17
    - jaxlib==0.4.17
    - ml-collections==0.1.1
    - optax==0.1.7
    - pandas==2.0.0
    - git+https://github.com/dirmeier/sbijax.git@v0.1.3
    - surjectors==0.2.4
    - tfp-nightly==0.20.0.dev20230404
    - diffrax==0.4.1

